version: "3.8"

services:
  taiga-task-master:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: taiga-task-master:latest
    container_name: taiga-task-master-webhook
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      # Webhook Configuration
      - WEBHOOK_TOKEN=${WEBHOOK_TOKEN}
      - PORT=3000

      # Taiga API Configuration
      - TAIGA_BASE_URL=${TAIGA_BASE_URL:-https://api.taiga.io}
      - TAIGA_USERNAME=${TAIGA_USERNAME}
      - TAIGA_PASSWORD=${TAIGA_PASSWORD}
      - TAIGA_PROJECT_ID=${TAIGA_PROJECT_ID}

      # AI API Keys (if using AI features)
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - taiga-network
    labels:
      - "com.taiga-task-master.service=webhook"
      - "com.taiga-task-master.version=1.0.0"

networks:
  taiga-network:
    driver: bridge
    name: taiga-task-master-network
