version: '3.8'

services:
  frontend:
    build:
      context: ../../
      dockerfile: packages/tasks-machine-simulator-frontend/Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - SERVICE_FQDN_FRONTEND_80
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: tasks-machine-simulator-frontend